before:
  hooks:
    - go mod tidy
builds:
- binary: cipherbin
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: cipherbin
    github:
      owner: cipherbin
      name: homebrew-cipherbin
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    description: "CLI tool for communicating with cipherbin to interact with messages"
    dependencies:
      - git
      - zsh
    install: |
      bin.install "cipherbin"