before:
  hooks:
    - go mod tidy
builds:
- binary: cipherbin
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: cipherbin
    url_template: "https://github.com/cipherbin/cipher-bin-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: Formula
    description: "CLI tool for communicating with cipherbin to interact with messages"
    dependencies:
      - git
      - zsh
    repository:
      owner: cipherbin
      name: homebrew-cipherbin
      token: "{{ .Env.GITHUB_TOKEN }}"
    install: |
      bin.install "cipherbin"
